        {{ HTML::script('scripts/jquery-1.10.2.min.js') }}
        {{ HTML::script('scripts/jquery-ui-1.10.3.custom.min.js') }}
        {{ HTML::script('scripts/jquery.colorbox-min.js') }}
        {{ HTML::script('scripts/jquery.flexslider-min.js') }}
        {{ HTML::script('scripts/slider.js') }}
        {{ HTML::script('scripts/jquery.selectbox-0.6.1.js') }}
        {{ HTML::script('scripts/twitter.js') }}
        {{ HTML::script('scripts/jflickrfeed.min.js') }}
        {{ HTML::script('scripts/superfish.js') }}
        {{ HTML::script('scripts/jquery.mobilemenu.min.js') }}
        {{ HTML::script('scripts/jquery.placeholder.min.js') }}
        {{ HTML::script('scripts/scripts.js') }}