		<script type="text/javascript" src="{{ URL::asset('scripts/jquery-1.10.2.min.js') }}"></script>
		<script type="text/javascript" src="{{ URL::asset('scripts/jquery-ui-1.10.3.custom.min.js') }}"></script>
		<script type="text/javascript" src="{{ URL::asset('scripts/jquery.colorbox-min.js') }}"></script>
		<script type="text/javascript" src="{{ URL::asset('scripts/jquery.flexslider-min.js') }}"></script>
		<script type="text/javascript" src="{{ URL::asset('scripts/slider.js') }}"></script>
		<script type="text/javascript" src="{{ URL::asset('scripts/jquery.selectbox-0.6.1.js') }}"></script>
		<script type="text/javascript" src="{{ URL::asset('scripts/twitter.js') }}"></script>
		<script type="text/javascript" src="{{ URL::asset('scripts/jflickrfeed.min.js') }}"></script>
		<script type="text/javascript" src="{{ URL::asset('scripts/superfish.js') }}"></script>
		<script type="text/javascript" src="{{ URL::asset('scripts/jquery.mobilemenu.min.js') }}"></script>
		<script type="text/javascript" src="{{ URL::asset('scripts/jquery.placeholder.min.js') }}"></script>
		<script type="text/javascript" src="{{ URL::asset('scripts/scripts.js') }}"></script>
