		<script type="text/javascript" src="scripts/jquery-1.10.2.min.js"></script>
		<script type="text/javascript" src="scripts/jquery-ui-1.10.3.custom.min.js"></script>
		<script type="text/javascript" src="scripts/jquery.colorbox-min.js"></script>
		<script type="text/javascript" src="scripts/jquery.flexslider-min.js"></script>
		<script type="text/javascript" src="scripts/slider.js"></script>
		<script type="text/javascript" src="scripts/jquery.selectbox-0.6.1.js"></script>
		<script type="text/javascript" src="scripts/twitter.js"></script>
		<script type="text/javascript" src="scripts/jflickrfeed.min.js"></script>
		<script type="text/javascript" src="scripts/superfish.js"></script>
		<script type="text/javascript" src="scripts/jquery.mobilemenu.min.js"></script>
		<script type="text/javascript" src="scripts/jquery.placeholder.min.js"></script>
		<script type="text/javascript" src="scripts/scripts.js"></script>